# Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docassemble.fullname" . }}-db-secret
  labels:
    {{- include "docassemble.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}

---
# Admin Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docassemble.fullname" . }}-admin-secret
  labels:
    {{- include "docassemble.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.docassemble.admin.password | b64enc }}

---
# Supervisor Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docassemble.fullname" . }}-supervisor-secret
  labels:
    {{- include "docassemble.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.docassemble.supervisor.password | b64enc }}

{{- if .Values.docassemble.storage.s3.enabled }}
---
# S3 Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docassemble.fullname" . }}-s3-secret
  labels:
    {{- include "docassemble.labels" . | nindent 4 }}
type: Opaque
data:
  secretKey: {{ .Values.docassemble.storage.s3.secretKey | b64enc }}
{{- end }}