apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docassemble.fullname" . }}-ssl-cert
  labels:
    {{- include "docassemble.labels" . | nindent 4 }}
data:
  prod-ca-2021.crt: |
{{ .Files.Get "ssl-certs/prod-ca-2021.crt" | indent 4 }}